parameters:
#    esi_inscriptions.example.class: Esi\InscriptionsBundle\Example

services:
#    esi_inscriptions.example:
#        class: %esi_inscriptions.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
